/* config.h.  Generated by configure.  */
#define HAVE_JPEG 1
#define HAVE_TIFF 1
#define HAVE_FREETYPE 1
#define HAVE_FREETYPE2 1
#define HAVE_GIF 0
#define GIFLIB_BUG_FIXED 0
#define HAVE_PNG 1
#define HAVE_XPM 0
