#*********************************************************************#
#                                                                     #
#                          Caml Images                                #
#                                                                     #
#            François Pessaux, projet Cristal, INRIA Rocquencourt     #
#            Pierre Weis, projet Cristal, INRIA Rocquencourt          #
#            Jun Furuse, projet Cristal, INRIA Rocquencourt           #
#                                                                     #
#  Copyright 1999-2004,                                               #
#  Institut National de Recherche en Informatique et en Automatique.  #
#  Distributed only by permission.                                    #
#                                                                     #
#*********************************************************************#

#(* $Id: Makefile.config.in,v 1.28 2004/10/02 15:49:05 weis Exp $ *)

PACKAGE=camlimages
VERSION=2.2.0

MV=mv -f
RM=rm -fR
CP=cp -pfR

CAMLDIR=/usr/lib/ocaml
LIBDIR=/usr/lib/ocaml/camlimages

CAMLC = ocamlc 
CAMLOPT = ocamlopt 
CAMLC_LABEL = ocamlc -labels
CAMLOPT_LABEL = ocamlopt -labels
CAMLDEP = ocamldep
CAMLLEX = ocamllex
CAMLYACC = ocamlyacc
CAMLMKTOP = ocamlmktop
CAMLMKLIB = ocamlmklib
CUSTOM=-custom

SUPPORTED=  lablgtk2 lablgl bmp ppm png jpeg tiff freetype(2) ps

SUPPORT_GIF=false
SUPPORT_PNG=true
SUPPORT_JPEG=true
SUPPORT_TIFF=true
SUPPORT_FREETYPE=true
SUPPORT_FREETYPE2=true
SUPPORT_PS=true
SUPPORT_LABLGTK=false
SUPPORT_GDKPIXBUF=
SUPPORT_LABLGTK2=false

LIBGIF=
LIBBMP=
LIBJPEG=-ljpeg
LIBTIFF=-ltiff
LIBFREETYPE=-lfreetype -lz
LIBPNG=-lpng -lz
LIBXVTHUMB=
LIBXPM=
LIBPPM=
LIBPS=

CFLAGS=-O0 -g3 -ggdb3
LDFLAGS=
X_CFLAGS=

INCLUDE_FREETYPE=-I/usr/include/freetype2

LABLGTKDIR=.
LABLGTK2DIR=/usr/lib/ocaml/lablgtk2

RANLIB=ranlib

LIBPREFIX =	ci_

WITH_UNIX=	unix.cma

WITH_CORELIB  = $(LIBPREFIX)core.cma

WITH_GRAPHICS =	graphics.cma $(LIBPREFIX)graphics.cma

WITH_GIF = 	$(LIBPREFIX)gif.cma

WITH_JPEG =	$(LIBPREFIX)jpeg.cma

WITH_TIFF =	$(LIBPREFIX)tiff.cma

WITH_XPM =	$(LIBPREFIX)xpm.cma

WITH_BMP =	$(LIBPREFIX)bmp.cma

WITH_PPM =	$(LIBPREFIX)ppm.cma

WITH_XVTHUMB=	$(LIBPREFIX)xvthumb.cma

WITH_PNG =	$(LIBPREFIX)png.cma

WITH_PS =	$(LIBPREFIX)ps.cma

WITH_FREETYPE=	$(LIBPREFIX)freetype.cma

WITH_CAMLIMAGES = $(WITH_CORELIB) $(WITH_GRAPHICS) $(WITH_FREETYPE) \
	$(WITH_GIF) $(WITH_JPEG) $(WITH_TIFF) $(WITH_BMP) $(WITH_PPM) \
        $(WITH_PNG) $(WITH_XVTHUMB) $(WITH_XPM) $(WITH_PS)

# only lablgtk_img lablgtk2_img is separated from $(WITH_CAMLIMAGES)

WITH_LABLGTKIMAGE = $(LIBPREFIX)lablgtk.cma
WITH_LABLGTK2IMAGE = $(LIBPREFIX)lablgtk2.cma

######################################

COMPFLAGS_CAMLIMAGES= -I $(LIBDIR)
LINKFLAGS_CAMLIMAGES= $(addprefix -ccopt \"-L, $(addsuffix\", $(LIBDIR))) $(WITH_CAMLIMAGES)
