#*********************************************************************#
#                                                                     #
#                          Caml Images                                #
#                                                                     #
#            Pierre Weis, projet Cristal, INRIA Rocquencourt          #
#                                                                     #
#  Copyright 2004 Institut National de Recherche en Informatique et   #
#  en Automatique.  Distributed only by permission.                   #
#                                                                     #
#*********************************************************************#

#(* $Id: Makefile,v 1.2 2004/10/02 14:20:09 weis Exp $ *)

include ../Makefile.config

all: eng.htm

clean::
	$(RM) *~
